meta_product_name: "X-Goal Achiever"
meta_title: "X-Goal Achiever - Accomplish your tasks!"
meta_description: "The application helps the user to track tasks, review the statistics, and improve over time."
meta_image: "og-default.png"
twitter_account: "@product_twitter_account"
